src/Acme/JobeetBundle/Entity/Job.php
<?php

namespace Acme\JobeetBundle\Entity;

use Acme\JobeetBundle\Utils\Jobeet as Jobeet;
use Doctrine\ORM\Mapping as ORM;

/**
 * Job
 */
class Job
{

    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $type;

    /**
     * @var string
     */
    private $company;

    /**
     * @var string
     */
    private $logo;

    /**
     * @var string
     */
    private $url;

    /**
     * @var string
     */
    private $position;

    /**
     * @var string
     */
    private $location;

    /**
     * @var string
     */
    private $description;

    /**
     * @var string
     */
    private $how_to_apply;

    /**
     * @var string
     */
    private $token;

    /**
     * @var boolean
     */
    private $is_public;

    /**
     * @var boolean
     */
    private $is_activated;

    /**
     * @var string
     */
    private $email;

    /**
     * @var \DateTime
     */
    private $expires_at;

    /**
     * @var string
     */
    private $created_at;

    /**
     * @var string
     */
    private $updated_at;

    /**
     * @var \Acme\JobeetBundle\Entity\Category
     */
    private $Category;

    public $file;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set type
     *
     * @param string $type
     * @return Job
     */
    public function setType($type)
    {
        $this->type = $type;
    
        return $this;
    }

    /**
     * Get type
     *
     * @return string 
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set company
     *
     * @param string $company
     * @return Job
     */
    public function setCompany($company)
    {
        $this->company = $company;
    
        return $this;
    }

    /**
     * Get company
     *
     * @return string 
     */
    public function getCompany()
    {
        return $this->company;
    }

    /**
     * Set logo
     *
     * @param string $logo
     * @return Job
     */
    public function setLogo($logo)
    {
        $this->logo = $logo;
    
        return $this;
    }

    /**
     * Get logo
     *
     * @return string 
     */
    public function getLogo()
    {
        return $this->logo;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Job
     */
    public function setUrl($url)
    {
        $this->url = $url;
    
        return $this;
    }

    /**
     * Get url
     *
     * @return string 
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set position
     *
     * @param string $position
     * @return Job
     */
    public function setPosition($position)
    {
        $this->position = $position;
    
        return $this;
    }

    /**
     * Get position
     *
     * @return string 
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Set location
     *
     * @param string $location
     * @return Job
     */
    public function setLocation($location)
    {
        $this->location = $location;
    
        return $this;
    }

    /**
     * Get location
     *
     * @return string 
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Job
     */
    public function setDescription($description)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set how_to_apply
     *
     * @param string $howToApply
     * @return Job
     */
    public function setHowToApply($howToApply)
    {
        $this->how_to_apply = $howToApply;
    
        return $this;
    }

    /**
     * Get how_to_apply
     *
     * @return string 
     */
    public function getHowToApply()
    {
        return $this->how_to_apply;
    }

    /**
     * Set token
     *
     * @param string $token
     * @return Job
     */
    public function setToken($token)
    {
        $this->token = $token;
    
        return $this;
    }

    /**
     * Get token
     *
     * @return string 
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Set is_public
     *
     * @param boolean $isPublic
     * @return Job
     */
    public function setIsPublic($isPublic)
    {
        $this->is_public = $isPublic;
    
        return $this;
    }

    /**
     * Get is_public
     *
     * @return boolean 
     */
    public function getIsPublic()
    {
        return $this->is_public;
    }

    /**
     * Set is_activated
     *
     * @param boolean $isActivated
     * @return Job
     */
    public function setIsActivated($isActivated)
    {
        $this->is_activated = $isActivated;
    
        return $this;
    }

    /**
     * Get is_activated
     *
     * @return boolean 
     */
    public function getIsActivated()
    {
        return $this->is_activated;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Job
     */
    public function setEmail($email)
    {
        $this->email = $email;
    
        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set expires_at
     *
     * @param \DateTime $expiresAt
     * @return Job
     */
    public function setExpiresAt($expiresAt)
    {
        $this->expires_at = $expiresAt;
    
        return $this;
    }

    /**
     * Get expires_at
     *
     * @return \DateTime 
     */
    public function getExpiresAt()
    {
        return $this->expires_at;
    }

    /**
     * Set created_at
     *
     * @param string $createdAt
     * @return Job
     */
    public function setCreatedAt($createdAt)
    {
        $this->created_at = $createdAt;
    
        return $this;
    }

    /**
     * Get created_at
     *
     * @return string 
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set updated_at
     *
     * @param string $updatedAt
     * @return Job
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updated_at = $updatedAt;
    
        return $this;
    }

    /**
     * Get updated_at
     *
     * @return string 
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Set Category
     *
     * @param \Acme\JobeetBundle\Entity\Category $category
     * @return Job
     */
    public function setCategory(\Acme\JobeetBundle\Entity\Category $category)
    {
        $this->Category = $category;
    
        return $this;
    }

    /**
     * Get Category
     *
     * @return \Acme\JobeetBundle\Entity\Category 
     */
    public function getCategory()
    {
        return $this->Category;
    }
    /**
     * @ORM\PrePersist
     */
    public function prePersistEvent()
    {
        $this->created_at = new \DateTime();
        if (!$this->getExpiresAt()) {
            $now = $this->getCreatedAt() ? $this->getCreatedAt()->format('U') : time();
            $this->expires_at = new \DateTime(date('Y-m-d H:i:s', $now + 86400 * 30));
        }
 
        return $this;
    }

    /**
     * @ORM\PreUpdate
     */
    public function preUpdateEvent()
    {
        $this->updated_at = new \DateTime();
 
        return $this;
    }

    public function __toString(){
        return sprintf('%s at %s (%s)', $this->getPosition(),
            $this->getCompany(), $this->getLocation());
    }

    public function getCompanySlug()
    {
        return Jobeet::slugify($this->getCompany());
    }

    public function getPositionSlug()
    {
        return Jobeet::slugify($this->getPosition());
    }

    public function getLocationSlug()
    {
        return Jobeet::slugify($this->getLocation());
    }

    public static function getTypes()
    {
        return array('full-time' => 'Full time',
                      'part-time' => 'Part time',
                      'freelance' => 'Freelance');
    }

    public static function getTypeValues()
    {
        return array_keys(self::getTypes());
    }

    protected function getUploadDir()
    {
        return 'uploads/jobs';
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web/'. $this->getUploadDir();
    }

    public function getWebPath()
    {
        return null === $this->logo ? null : $this->getUploadDir().'/'.$this->logo;
    }

    public function getAbsolutePath()
    {
        return null === $this->logo ? null : $this->getUploadRootDir().'/'.$this->logo;
    }


    /**
     * @ORM\PostPersist
     */
    public function upload()
    {
        if (null === $this->file) {
            return;
        }

        // If there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->file->move($this->getUploadRootDir(), $this->logo);

        unset($this->file);
    }

    /**
     * @ORM\PostRemove
     */
    public function removeUpload()
    {
        if (file_exists($file)) {
            if ($file = $this->getAbsolutePath()) {
                unlink($file);
            }
        }
    }

    /**
     * @ORM\PrePersist
     */
    public function preUpload()
    {
        if (Null !== $this->file) {
            $this->logo = uniqid().'.'.$this->file->guessExtension();
        }
    }

    /**
     * @ORM\PrePersist
     */
    public function setTokenValue()
    {
        if (!$this->getToken()) {
            $this->token = sha1($this->getEmail().dand(11111,99999));
        }
    }

src/Acme/JobeetBundle/Form/JobType.php
<?php

namespace Acme\JobeetBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Acme\JobeetBundle\Entity\Job;

class JobType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            // type is a varchar in the schema but we want its value to be 
            // restricted to a list of choices: full-time, part-time, freelance
            ->add('type', 'choice', array('choices' => Job::getTypes(),
                                          'expanded' => true))
            ->add('Category')
            ->add('company')
            ->add('file', 'file', array('label'=>'Company logo',
                                        'required' => false))
            ->add('url')
            ->add('position')
            ->add('location')
            ->add('description')
            ->add('how_to_apply', null, array('label'=>'How to apply'))
            ->add('is_public', null, array('label'=>'Public?'))
            //->add('is_activated')
            ->add('email')
            //->add('expires_at')
            //->add('created_at')
            //->add('updated_at')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Acme\JobeetBundle\Entity\Job'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'acme_jobeetbundle_job';
    }
}

src/Acme/JobeetBundle/Resources/views/Job/admin.html.twig
<div id="job_actions">
	<h3>Admin</h3>
	<ul>
		{% if not job.isActivated %}
			<li><a href="{{ path('job_edit', {'token': job.token}) }}">
				Edit
			</a></li>
			<li>
				<form action="{{ path('job_publish', {'token': job.token}) }}" method="post">
					{{ form_widget(publish_form) }}
					<button type="submit">Publish</button>
					</form>
			</li>
		{% endif %}
		<li>
			<form action="{{ path('job_delete', {'token': job.token }) }}" method="post">
				{{ form_widget(delete_form) }}
				<button type="submit" onclick="if(!confirm('Are you sure?')) { return false; }">Delete</button>
			</form>
		</li>

		{% if job.isActivated %}
			<li {% if job.expiresSoon %} class="expires_soon" {% endif %}>
				{% if job.isExpired %}
					Expired
				{% else %}
					Expires in <strong>{{ job.getDaysBeforeExpires }}</strong days
				{% endif %}

				{% if job.expiresSoon %}
					<form action="{{ path('job_extend', { 'token': job.token }) }}" method="post">
						{{ form_widget(extend_form) }}
						<button type="submit">Extend</button> for another 30 days
				{% endif %}
			</li>
		{% else %}
			<li>
				[Bookmark this <a href="{{ url('job_preview', {'token': job.token, 'company': job.companySlug, 'location': job.locationSlug, 'position': job.positionSlug }) }}">URL</a> to manage this job in the future.]
			</li>
		{% endif %}
	</ul>
</div>

src/Acme/JobeetBundle/Resources/views/Job/edit.html.twig
{% extends 'AcmeJobeetBundle::layout.html.twig' %}

{% form_theme edit_form _self %}
 
{% block form_errors %}
{% spaceless %}
    {% if errors|length > 0 %}
        <ul class="error_list">
            {% for error in errors %}
                <li>{{ error.messageTemplate|trans(error.messageParameters, 'validators') }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endspaceless %}
{% endblock form_errors %}
 
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/acmejobeet/css/job.css') }}" type="text/css" media="all" />
{% endblock %}
 
{% block content %}
    <h1>Job edit</h1>
    <form action="{{ path('job_update', { 'token': entity.token }) }}" method="post" {{ form_enctype(edit_form) }}>
        <table id="job_form">
            <tfoot>
                <tr>
                    <td colspan="2">
                        <input type="submit" value="Preview your job" />
                    </td>
                </tr>
            </tfoot>
            <tbody>
                <tr>
                    <th>{{ form_label(edit_form.Category) }}</th>
                    <td>
                        {{ form_errors(edit_form.Category) }}
                        {{ form_widget(edit_form.Category) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(edit_form.type) }}</th>
                    <td>
                        {{ form_errors(edit_form.type) }}
                        {{ form_widget(edit_form.type) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(edit_form.company) }}</th>
                    <td>
                        {{ form_errors(edit_form.company) }}
                        {{ form_widget(edit_form.company) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(edit_form.file) }}</th>
                    <td>
                        {{ form_errors(edit_form.file) }}
                        {{ form(edit_form.file) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(edit_form.url) }}</th>
                    <td>
                        {{ form_errors(edit_form.url) }}
                        {{ form_widget(edit_form.url) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(edit_form.position) }}</th>
                    <td>
                        {{ form_errors(edit_form.position) }}
                        {{ form_widget(edit_form.position) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(edit_form.location) }}</th>
                    <td>
                        {{ form_errors(edit_form.location) }}
                        {{ form_widget(edit_form.location) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(edit_form.description) }}</th>
                    <td>
                        {{ form_errors(edit_form.description) }}
                        {{ form_widget(edit_form.description) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(edit_form.how_to_apply) }}</th>
                    <td>
                        {{ form_errors(edit_form.how_to_apply) }}
                        {{ form_widget(edit_form.how_to_apply) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(edit_form.is_public) }}</th>
                    <td>
                        {{ form_errors(edit_form.is_public) }}
                        {{ form_widget(edit_form.is_public) }}
                        <br /> Whether the job can also be published on affiliate websites or not.
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(edit_form.email) }}</th>
                    <td>
                        {{ form_errors(edit_form.email) }}
                        {{ form_widget(edit_form.email) }}
                    </td>
                </tr>
            </tbody>
        </table>
    {{ form_end(edit_form) }}
{% endblock %}

src/Acme/JobeetBundle/Resources/views/Job/index.atom.twig
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
	<title>Jobeet</title>
	<subtitle>Latest Jobs</subtitle>
	<link href="{{ url('job', { '_format': 'atom'}) }}" rel="self"/>
	<link href="{{ url('AcmeJobeetBundle_homepage') }}"/>
	<updated>{{ lastUpdated }}</updated>
	<author><name>Jobeet</name></author>
	<id>{{ feedId }}</id>
	
	{% for category in categories %}
		{% for entity in category.activejobs %}
			<entry>
				<title>{{ entry.position}} ({{ entity.location }})</title>
				<link href="{{ url('job_show', {'id': entity.id, 'company': entity.companyslug, 'location': entity.locationslug, 'position': positionslug}) }}" />
				<id>{{ entity.id }}</id>
				<updated>{{ entity.createdAt.format(constant('DATE_ATOM')) }}</updated>
				<summary type="xhtml">
					<div xmlns="http://www.w3.orm/1999/xhtml">
						{% if entity.logo %}
							<div>
								<a href="{{ entity.url }}">
									<img src="http://{{ app.request.host }}/uploads/jobs/{{ entity.logo }}" alt="{{entity.company }}" logo />
								</a>
							</div>
						{% endif %}
						<div>
							{{ entity.description|nl2br }}
						</div>
						<h4>How to apply?</h4>
						<p>{{ entity.howtoapply }}</p>
					</div>
				</summary>
				<author><name>{{ author.company }}</name></author>
			</entry>
		{% endfor %}
	{% endfor %}
</feed>

src/Acme/JobeetBundle/Resources/views/Job/index.html.twig
{% extends 'AcmeJobeetBundle::layout.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/AcmeJobeet/css/jobs.css') }}" type="text/css" media="all" />
{% endblock %}

{% block content %}
  <div id="jobs">
    {% for category in categories %}
      <div class="category_{{ category.slug }}">
        <div class="category">
          <div class="feed">
            <a href="{{ path('AcmeJobeetBundle_category', { 'slug': category.slug, '_format': 'atom' }) }}">Feed</a>
          </div>
          <h1> <a href="{{ path('AcmeJobeetBundle_category', { 'slug': category.slug })}}">
            {{ category.name }}</a></h1>
        </div>

        {{ include ('AcmeJobeetBundle:Job:list.html.twig', {'jobs':category.activejobs })}}

        {% if category.morejobs %}
          <div class="more_jobs">
            and <a href="{{ path('AcmeJobeetBundle_category', { 'slug': category.slug })}}">
            {{ category.morejobs }}</a>
            more
          </div>
        {% endif %}
      </div>
    {% endfor %}
  </div>
{% endblock %}

src/Acme/JobeetBundle/Resources/views/Job/list.html.twig
 <table class="jobs">
	{% for entity in category.activejobs %}
		<tr class="{{ cycle(['even', 'odd'], loop.index) }}">
			<td class="location">{{ entity.location }}</td>
				<td class="position">
					<a href="{{ path('job_show', { 'id': entity.id, 'company': entity.companyslug, 'location': entity.locationslug, 'position': entity.positionslug }) }}">
					{{ entity.position }}
					</a>
				</td>
			<td class="company">{{ entity.company }}</td>
		</tr>
	{% endfor %}
</table>

src/Acme/JobeetBundle/Resources/views/Job/new.html.twig
{% extends 'AcmeJobeetBundle::layout.html.twig' %}

{% form_theme form _self %}

{% block form_errors %}
{% spaceless %}
	{% if errors|length > 0 %}
		<ul class="error_list">
			{% for error in errors %}
				<li>
					{{ error.messageTemplate|trans(error.messageParameters, 'validators') }}
				</li>
			{% endfor %}
		</ul>
	{% endif %}
{% endspaceless %}
{% endblock form_errors %}

{% block stylesheets %}
	{{ parent() }}
	<link rel="stylesheet" href="{{ asset('bundles/acmejobeet/css/job.css') }}" type="text/css" media="all" />
{% endblock %}

{% block content %}
 <h1>Job creation</h1>
    <form action="{{ path('job_create') }}" method="post" {{ form_enctype(form) }}>
        <table id="job_form">
            <tfoot>
                <tr>
                    <td colspan="2">
                        <input type="submit" value="Preview your job" />
                    </td>
                </tr>
            </tfoot>
            <tbody>
                <tr>
                    <th>{{ form_label(form.Category) }}</th>
                    <td>
                        {{ form_errors(form.Category) }}
                        {{ form_widget(form.Category) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(form.type) }}</th>
                    <td>
                        {{ form_errors(form.type) }}
                        {{ form_widget(form.type) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(form.company) }}</th>
                    <td>
                        {{ form_errors(form.company) }}
                        {{ form_widget(form.company) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(form.file) }}</th>
                    <td>
                        {{ form_errors(form.file) }}
                        {{ form_widget(form.file) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(form.url) }}</th>
                    <td>
                        {{ form_errors(form.url) }}
                        {{ form_widget(form.url) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(form.position) }}</th>
                    <td>
                        {{ form_errors(form.position) }}
                        {{ form_widget(form.position) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(form.location) }}</th>
                    <td>
                        {{ form_errors(form.location) }}
                        {{ form_widget(form.location) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(form.description) }}</th>
                    <td>
                        {{ form_errors(form.description) }}
                        {{ form_widget(form.description) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(form.how_to_apply) }}</th>
                    <td>
                        {{ form_errors(form.how_to_apply) }}
                        {{ form_widget(form.how_to_apply) }}
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(form.is_public) }}</th>
                    <td>
                        {{ form_errors(form.is_public) }}
                        {{ form_widget(form.is_public) }}
                        <br /> Whether the job can also be published on affiliate websites or not.
                    </td>
                </tr>
                <tr>
                    <th>{{ form_label(form.email) }}</th>
                    <td>
                        {{ form_errors(form.email) }}
                        {{ form_widget(form.email) }}
                    </td>
                </tr>
            </tbody>
        </table>
    {{ form_end(form) }}
{% endblock %}

src/Acme/JobeetBundle/Resources/views/Job/show.html.twig
{% extends 'AcmeJobeetBundle::layout.html.twig' %}

{% block title %}
    {{entity.company }} is looking for a {{ entity.position }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{asset('bundles/acmejobeet/css/job.css') }}" type="text/css" media="all" />
{% endblock %}

{% block content %}
    {% if app.request.get('token') %}
        {% include 'AcmeJobeetBundle:Job:admin.html.twig' with { 'job': entity } %}
    {% endif %}
    <div id="job">
        <h1>{{ entity.company }}</h1>
        <h2>{{ entity.location }}</h2>
        <h3>
            {{ entity.position }}
            <small> - {{ entity.type }}</small>
        </h3>

        {% if entity.logo %}
            <div class="logo">
                <a href="{{ entity.url }}">
                    <img src="/uploads/jobs/{{ entity.logo }}" alt="{{ entity.company }} logo" />
                </a>
            </div>
        {% endif %}

        <div class="description">
            {{ entity.description|nl2br }}
        </div>

        <h4>How to apply?</h4>

        <p class="hot_to_apply">{{ entity.howtoapply }}</p>

        <div class="meta">
            <small>posted on {{ entity.createdat|date('m/d/Y') }}</small>
        </div>

        {# <div style="padding: 20px 0">
            <a href="{{ path('job_edit', { 'token': entity.token}) }}">
                Edit
            </a>
        </div> #}
    </div>
{% endblock %}